// prisma/seed-hsk2.ts  (hoặc thay luôn vào seed.ts nếu bạn muốn chỉ có HSK 2)
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const flashcards = [
  { chinese: '吧', pinyin: 'ba', meaning: 'nhé, chứ, đúng không', hskLevel: 2 },
  { chinese: '白', pinyin: 'bái', meaning: 'trắng, trắng tinh, miễn phí', hskLevel: 2 },
  { chinese: '百', pinyin: 'bǎi', meaning: 'trăm, một trăm', hskLevel: 2 },
  { chinese: '帮助', pinyin: 'bāngzhù', meaning: 'giúp đỡ, hỗ trợ', hskLevel: 2 },
  { chinese: '报纸', pinyin: 'bàozhǐ', meaning: 'báo chí, tờ báo', hskLevel: 2 },
  { chinese: '比', pinyin: 'bǐ', meaning: 'so sánh, hơn, tỷ lệ', hskLevel: 2 },
  { chinese: '别', pinyin: 'bié', meaning: 'đừng, khác, chia tay', hskLevel: 2 },
  { chinese: '长', pinyin: 'cháng', meaning: 'dài, thường xuyên', hskLevel: 2 },
  { chinese: '唱歌', pinyin: 'chàng gē', meaning: 'hát, ca hát', hskLevel: 2 },
  { chinese: '出', pinyin: 'chū', meaning: 'ra, đi ra, xuất hiện', hskLevel: 2 },
  { chinese: '穿', pinyin: 'chuān', meaning: 'mặc (quần áo), mang (giày)', hskLevel: 2 },
  { chinese: '船', pinyin: 'chuán', meaning: 'thuyền, tàu thủy', hskLevel: 2 },
  { chinese: '次', pinyin: 'cì', meaning: 'lần, thứ tự', hskLevel: 2 },
  { chinese: '从', pinyin: 'cóng', meaning: 'từ, theo, từ lúc', hskLevel: 2 },
  { chinese: '错', pinyin: 'cuò', meaning: 'sai, nhầm, lỗi', hskLevel: 2 },
  { chinese: '打篮球', pinyin: 'dǎ lánqiú', meaning: 'chơi bóng rổ', hskLevel: 2 },
  { chinese: '大家', pinyin: 'dàjiā', meaning: 'mọi người, tất cả', hskLevel: 2 },
  { chinese: '但是', pinyin: 'dànshì', meaning: 'nhưng, thế nhưng', hskLevel: 2 },
  { chinese: '到', pinyin: 'dào', meaning: 'đến, tới nơi', hskLevel: 2 },
  { chinese: '得', pinyin: 'de', meaning: '(trợ từ bổ nghĩa)', hskLevel: 2 },
  { chinese: '得', pinyin: 'děi', meaning: 'phải, cần phải', hskLevel: 2 },
  { chinese: '弟弟', pinyin: 'dìdi', meaning: 'em trai', hskLevel: 2 },
  { chinese: '第一', pinyin: 'dì yī', meaning: 'thứ nhất, số một', hskLevel: 2 },
  { chinese: '懂', pinyin: 'dǒng', meaning: 'hiểu, biết', hskLevel: 2 },
  { chinese: '房间', pinyin: 'fángjiān', meaning: 'phòng, căn phòng', hskLevel: 2 },
  { chinese: '非常', pinyin: 'fēicháng', meaning: 'rất, cực kỳ', hskLevel: 2 },
  { chinese: '服务员', pinyin: 'fúwùyuán', meaning: 'nhân viên phục vụ', hskLevel: 2 },
  { chinese: '高', pinyin: 'gāo', meaning: 'cao, cao cấp', hskLevel: 2 },
  { chinese: '告诉', pinyin: 'gàosù', meaning: 'nói cho biết, bảo', hskLevel: 2 },
  { chinese: '哥哥', pinyin: 'gēge', meaning: 'anh trai', hskLevel: 2 },
  { chinese: '给', pinyin: 'gěi', meaning: 'cho, đưa cho', hskLevel: 2 },
  { chinese: '公共汽车', pinyin: 'gōnggòng qìchē', meaning: 'xe buýt', hskLevel: 2 },
  { chinese: '公斤', pinyin: 'gōngjīn', meaning: 'ki-lô-gam', hskLevel: 2 },
  { chinese: '公司', pinyin: 'gōngsī', meaning: 'công ty', hskLevel: 2 },
  { chinese: '贵', pinyin: 'guì', meaning: 'đắt, quý', hskLevel: 2 },
  { chinese: '还', pinyin: 'hái', meaning: 'vẫn còn, nữa', hskLevel: 2 },
  { chinese: '孩子', pinyin: 'háizi', meaning: 'đứa trẻ, con cái', hskLevel: 2 },
  { chinese: '好吃', pinyin: 'hǎochī', meaning: 'ngon, delicious', hskLevel: 2 },
  { chinese: '号', pinyin: 'hào', meaning: 'số, ngày (trong tháng)', hskLevel: 2 },
  { chinese: '黑', pinyin: 'hēi', meaning: 'đen, tối', hskLevel: 2 },
  { chinese: '红', pinyin: 'hóng', meaning: 'đỏ, màu đỏ', hskLevel: 2 },
  { chinese: '欢迎', pinyin: 'huānyíng', meaning: 'hoan nghênh, chào đón', hskLevel: 2 },
  { chinese: '还', pinyin: 'huán', meaning: 'trả lại, hoàn lại', hskLevel: 2 },
  { chinese: '回答', pinyin: 'huídá', meaning: 'trả lời, đáp', hskLevel: 2 },
  { chinese: '机场', pinyin: 'jīchǎng', meaning: 'sân bay', hskLevel: 2 },
  { chinese: '鸡蛋', pinyin: 'jīdàn', meaning: 'trứng gà', hskLevel: 2 },
  { chinese: '件', pinyin: 'jiàn', meaning: 'cái (đồ vật, sự việc)', hskLevel: 2 },
  { chinese: '教室', pinyin: 'jiàoshì', meaning: 'phòng học', hskLevel: 2 },
  { chinese: '姐姐', pinyin: 'jiějie', meaning: 'chị gái', hskLevel: 2 },
  { chinese: '介绍', pinyin: 'jièshào', meaning: 'giới thiệu', hskLevel: 2 },
  { chinese: '进', pinyin: 'jìn', meaning: 'vào, tiến vào', hskLevel: 2 },
  { chinese: '近', pinyin: 'jìn', meaning: 'gần, gần đây', hskLevel: 2 },
  { chinese: '就', pinyin: 'jiù', meaning: 'liền, thì, chỉ', hskLevel: 2 },
  { chinese: '觉得', pinyin: 'juéde', meaning: 'cảm thấy, thấy rằng', hskLevel: 2 },
  { chinese: '咖啡', pinyin: 'kāfēi', meaning: 'cà phê', hskLevel: 2 },
  { chinese: '开始', pinyin: 'kāishǐ', meaning: 'bắt đầu', hskLevel: 2 },
  { chinese: '考试', pinyin: 'kǎoshì', meaning: 'thi cử, kỳ thi', hskLevel: 2 },
  { chinese: '可能', pinyin: 'kěnéng', meaning: 'có thể, có lẽ', hskLevel: 2 },
  { chinese: '可以', pinyin: 'kěyǐ', meaning: 'có thể, được phép', hskLevel: 2 },
  { chinese: '课', pinyin: 'kè', meaning: 'bài học, môn học', hskLevel: 2 },
  { chinese: '快', pinyin: 'kuài', meaning: 'nhanh, sắp', hskLevel: 2 },
  { chinese: '快乐', pinyin: 'kuàilè', meaning: 'vui vẻ, hạnh phúc', hskLevel: 2 },
  { chinese: '累', pinyin: 'lèi', meaning: 'mệt, mỏi', hskLevel: 2 },
  { chinese: '离', pinyin: 'lí', meaning: 'cách, rời khỏi', hskLevel: 2 },
  { chinese: '两', pinyin: 'liǎng', meaning: 'hai (khi đếm)', hskLevel: 2 },
  { chinese: '路', pinyin: 'lù', meaning: 'đường, tuyến đường', hskLevel: 2 },
  { chinese: '旅游', pinyin: 'lǚyóu', meaning: 'du lịch', hskLevel: 2 },
  { chinese: '卖', pinyin: 'mài', meaning: 'bán', hskLevel: 2 },
  { chinese: '慢', pinyin: 'màn', meaning: 'chậm, chậm chạp', hskLevel: 2 },
  { chinese: '忙', pinyin: 'máng', meaning: 'bận, bận rộn', hskLevel: 2 },
  { chinese: '每', pinyin: 'měi', meaning: 'mỗi, mọi', hskLevel: 2 },
  { chinese: '妹妹', pinyin: 'mèimei', meaning: 'em gái', hskLevel: 2 },
  { chinese: '门', pinyin: 'mén', meaning: 'cửa, môn (ngành)', hskLevel: 2 },
  { chinese: '男人', pinyin: 'nánrén', meaning: 'đàn ông, nam giới', hskLevel: 2 },
  { chinese: '您', pinyin: 'nín', meaning: 'ngài, bạn (lịch sự)', hskLevel: 2 },
  { chinese: '牛奶', pinyin: 'niúnǎi', meaning: 'sữa bò', hskLevel: 2 },
  { chinese: '女人', pinyin: 'nǚrén', meaning: 'phụ nữ, đàn bà', hskLevel: 2 },
  { chinese: '旁边', pinyin: 'pángbiān', meaning: 'bên cạnh, kế bên', hskLevel: 2 },
  { chinese: '跑步', pinyin: 'pǎobù', meaning: 'chạy bộ', hskLevel: 2 },
  { chinese: '便宜', pinyin: 'piányi', meaning: 'rẻ, tiện nghi', hskLevel: 2 },
  { chinese: '票', pinyin: 'piào', meaning: 'vé', hskLevel: 2 },
  { chinese: '妻子', pinyin: 'qīzi', meaning: 'vợ', hskLevel: 2 },
  { chinese: '起床', pinyin: 'qǐchuáng', meaning: 'thức dậy, dậy', hskLevel: 2 },
  { chinese: '千', pinyin: 'qiān', meaning: 'nghìn, một nghìn', hskLevel: 2 },
  { chinese: '晴', pinyin: 'qíng', meaning: 'nắng, trời quang', hskLevel: 2 },
  { chinese: '去年', pinyin: 'qùnián', meaning: 'năm ngoái', hskLevel: 2 },
  { chinese: '让', pinyin: 'ràng', meaning: 'nhường, để cho', hskLevel: 2 },
  { chinese: '上班', pinyin: 'shàngbān', meaning: 'đi làm, đi làm việc', hskLevel: 2 },
  { chinese: '身体', pinyin: 'shēntǐ', meaning: 'cơ thể, thân thể', hskLevel: 2 },
  { chinese: '生病', pinyin: 'shēngbìng', meaning: 'ốm, bị bệnh', hskLevel: 2 },
  { chinese: '生日', pinyin: 'shēngrì', meaning: 'sinh nhật', hskLevel: 2 },
  { chinese: '时间', pinyin: 'shíjiān', meaning: 'thời gian', hskLevel: 2 },
  { chinese: '事情', pinyin: 'shìqing', meaning: 'việc, sự việc', hskLevel: 2 },
  { chinese: '手表', pinyin: 'shǒubiǎo', meaning: 'đồng hồ đeo tay', hskLevel: 2 },
  { chinese: '手机', pinyin: 'shǒujī', meaning: 'điện thoại di động', hskLevel: 2 },
  { chinese: '送', pinyin: 'sòng', meaning: 'tặng, đưa, tiễn', hskLevel: 2 },
  { chinese: '所以', pinyin: 'suǒyǐ', meaning: 'vì vậy, cho nên', hskLevel: 2 },
  { chinese: '它', pinyin: 'tā', meaning: 'nó (vật)', hskLevel: 2 },
  { chinese: '踢', pinyin: 'tī', meaning: 'đá (bóng)', hskLevel: 2 },
  { chinese: '题', pinyin: 'tí', meaning: 'đề, câu hỏi', hskLevel: 2 },
  { chinese: '跳舞', pinyin: 'tiàowǔ', meaning: 'nhảy múa', hskLevel: 2 },
  { chinese: '外', pinyin: 'wài', meaning: 'ngoài, ngoại', hskLevel: 2 },
  { chinese: '完', pinyin: 'wán', meaning: 'xong, hết', hskLevel: 2 },
  { chinese: '玩', pinyin: 'wán', meaning: 'chơi, vui chơi', hskLevel: 2 },
  { chinese: '晚上', pinyin: 'wǎnshang', meaning: 'buổi tối', hskLevel: 2 },
  { chinese: '问', pinyin: 'wèn', meaning: 'hỏi', hskLevel: 2 },
  { chinese: '问题', pinyin: 'wèntí', meaning: 'vấn đề, câu hỏi', hskLevel: 2 },
  { chinese: '西瓜', pinyin: 'xīguā', meaning: 'dưa hấu', hskLevel: 2 },
  { chinese: '希望', pinyin: 'xīwàng', meaning: 'hy vọng, mong muốn', hskLevel: 2 },
  { chinese: '洗', pinyin: 'xǐ', meaning: 'rửa, giặt', hskLevel: 2 },
  { chinese: '小时', pinyin: 'xiǎoshí', meaning: 'giờ (thời gian)', hskLevel: 2 },
  { chinese: '笑', pinyin: 'xiào', meaning: 'cười', hskLevel: 2 },
  { chinese: '新', pinyin: 'xīn', meaning: 'mới', hskLevel: 2 },
  { chinese: '姓', pinyin: 'xìng', meaning: 'họ (tính)', hskLevel: 2 },
  { chinese: '休息', pinyin: 'xiūxi', meaning: 'nghỉ ngơi', hskLevel: 2 },
  { chinese: '雪', pinyin: 'xuě', meaning: 'tuyết', hskLevel: 2 },
  { chinese: '颜色', pinyin: 'yánsè', meaning: 'màu sắc', hskLevel: 2 },
  { chinese: '眼睛', pinyin: 'yǎnjing', meaning: 'mắt', hskLevel: 2 },
  { chinese: '羊肉', pinyin: 'yángròu', meaning: 'thịt cừu', hskLevel: 2 },
  { chinese: '药', pinyin: 'yào', meaning: 'thuốc', hskLevel: 2 },
  { chinese: '要', pinyin: 'yào', meaning: 'muốn, cần', hskLevel: 2 },
  { chinese: '也', pinyin: 'yě', meaning: 'cũng, cũng vậy', hskLevel: 2 },
  { chinese: '已经', pinyin: 'yǐjīng', meaning: 'đã rồi, đã', hskLevel: 2 },
  { chinese: '一起', pinyin: 'yīqǐ', meaning: 'cùng nhau', hskLevel: 2 },
  { chinese: '意思', pinyin: 'yìsi', meaning: 'ý nghĩa, ý tứ', hskLevel: 2 },
  { chinese: '阴', pinyin: 'yīn', meaning: 'âm (trời), u ám', hskLevel: 2 },
  { chinese: '因为', pinyin: 'yīnwèi', meaning: 'bởi vì', hskLevel: 2 },
  { chinese: '游泳', pinyin: 'yóuyǒng', meaning: 'bơi lội', hskLevel: 2 },
  { chinese: '右边', pinyin: 'yòubiān', meaning: 'bên phải', hskLevel: 2 },
  { chinese: '鱼', pinyin: 'yú', meaning: 'cá', hskLevel: 2 },
  { chinese: '元', pinyin: 'yuán', meaning: 'nguyên (đơn vị tiền)', hskLevel: 2 },
  { chinese: '远', pinyin: 'yuǎn', meaning: 'xa, xa xôi', hskLevel: 2 },
  { chinese: '运动', pinyin: 'yùndòng', meaning: 'vận động, thể thao', hskLevel: 2 },
  { chinese: '再', pinyin: 'zài', meaning: 'lại, nữa', hskLevel: 2 },
  { chinese: '早上', pinyin: 'zǎoshang', meaning: 'buổi sáng', hskLevel: 2 },
  { chinese: '张', pinyin: 'zhāng', meaning: 'trương (lượng từ giấy)', hskLevel: 2 },
  { chinese: '长', pinyin: 'zhǎng', meaning: 'trưởng, lớn lên', hskLevel: 2 },
  { chinese: '丈夫', pinyin: 'zhàngfu', meaning: 'chồng', hskLevel: 2 },
  { chinese: '找', pinyin: 'zhǎo', meaning: 'tìm, tìm kiếm', hskLevel: 2 },
  { chinese: '着', pinyin: 'zhe', meaning: '(trợ từ đang làm gì)', hskLevel: 2 },
  { chinese: '真', pinyin: 'zhēn', meaning: 'thật, thật sự', hskLevel: 2 },
  { chinese: '正在', pinyin: 'zhèngzài', meaning: 'đang, đang làm gì', hskLevel: 2 },
  { chinese: '知道', pinyin: 'zhīdào', meaning: 'biết, biết rõ', hskLevel: 2 },
  { chinese: '准备', pinyin: 'zhǔnbèi', meaning: 'chuẩn bị', hskLevel: 2 },
  { chinese: '自行车', pinyin: 'zìxíngchē', meaning: 'xe đạp', hskLevel: 2 },
  { chinese: '走', pinyin: 'zǒu', meaning: 'đi, đi bộ', hskLevel: 2 },
  { chinese: '最', pinyin: 'zuì', meaning: 'nhất, cực kỳ', hskLevel: 2 },
  { chinese: '左边', pinyin: 'zuǒbiān', meaning: 'bên trái', hskLevel: 2 },
]

async function main() {
  console.log('Đang seed 150 từ HSK 2...')
  const result = await prisma.flashCard.createMany({
    data: flashcards,
    skipDuplicates: true,
  })
  console.log(`Đã thêm thành công ${result.count} từ HSK 2!`)
}

main()
  .catch(e => {
    console.error('Lỗi:', e)
    process.exit(1)
  })
  .finally(async () => await prisma.$disconnect())